#a docker image from docker hub
FROM node:20-alpine

#Dir to work in 
WORKDIR /app

#First dot is the current dir and the second dot is the path to the currect dir within the container
COPY . .  

#command to run the app
CMD node hello.js
